NumPy - Numerical Python


In [29]:
import numpy as np


List vs Numpy - Time comparison

In [30]:
from time import process_time
python_list=[i for i in range(1000000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.11649888899999894


In [31]:
np_array=np.array([i for i in range(1000000)])
start_time=process_time()
np_array=np_array+5
end_time=process_time()
print(end_time-start_time)

0.0022287950000006163


NumPy Arrays

In [32]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [33]:
np_array=np.array([1,2,3,4,5])
print(np_array)
(type(np_array))

[1 2 3 4 5]


numpy.ndarray

In [34]:
# creating 1 Dim Np Array
np_array1=np.array([1,2,3,4,5])
print(np_array1)
np_array1.shape

[1 2 3 4 5]


(5,)

In [35]:
np_array2=np.array([(1,2,3),(3,4,5)])
print(np_array2)
np_array2.shape

[[1 2 3]
 [3 4 5]]


(2, 3)

In [36]:
#create array with zeros
np_array3=np.zeros((2,3))
print(np_array3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
#create array with ones
np_array4=np.ones((3,3))
print(np_array4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
# create a array with particular value
np_array5=np.full((3,3),5)
print(np_array5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [39]:
# create a array with identical
np_array6=np.eye(3)
print(np_array6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# create a array with random
np_array7=np.random.random((3,3))
print(np_array7)

[[0.10603837 0.32068935 0.38248177]
 [0.29991652 0.96939083 0.02869401]
 [0.32214168 0.18344543 0.30687141]]


In [41]:
c= np.random.randint(5,12,(3,3))
print(c)

[[ 5 11  7]
 [11  8  7]
 [ 9 10 10]]


**Mathematical Operations**

In [42]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
#np array runs element wise operation is available
a=np.random.randint(3,9,(3,3))
b=np.random.randint(3,9,(3,3))
print(a)
print(b)
print(a+b)

[[4 7 8]
 [8 5 5]
 [8 4 7]]
[[8 8 8]
 [8 5 3]
 [6 5 6]]
[[12 15 16]
 [16 10  8]
 [14  9 13]]


In [45]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[12 15 16]
 [16 10  8]
 [14  9 13]]
[[-4 -1  0]
 [ 0  0  2]
 [ 2 -1  1]]
[[32 56 64]
 [64 25 15]
 [48 20 42]]
[[0.5        0.875      1.        ]
 [1.         1.         1.66666667]
 [1.33333333 0.8        1.16666667]]


**Array Manipulations**

In [47]:
array=np.random.randint(1,10,(3,3))
print(array)
print(array.shape)

[[7 4 1]
 [8 3 5]
 [7 5 3]]
(3, 3)
